export const ranks = [
  { name: "Unranked",
    url: "/src/utils/iconsRank/SeasonalRank0-0.webp"
   },

  { name: "Herald_1" ,
    url: "/src/utils/iconsRank/SeasonalRank1-1.webp"},
  { name: "Herald_2" ,
    url: "/src/utils/iconsRank/SeasonalRank1-2.webp"},
  { name: "Herald_3" ,
    url: "/src/utils/iconsRank/SeasonalRank1-3.webp"},
  { name: "Herald_4" ,
    url: "/src/utils/iconsRank/SeasonalRank1-4.webp"},
  { name: "Herald_5",
    url: "/src/utils/iconsRank/SeasonalRank1-5.webp" },

  { name: "Guardian_1" ,
    url: "/src/utils/iconsRank/SeasonalRank2-1.webp"},
  { name: "Guardian_2" ,
    url: "/src/utils/iconsRank/SeasonalRank2-2.webp"},
  { name: "Guardian_3" ,
    url: "/src/utils/iconsRank/SeasonalRank2-3.webp"},
  { name: "Guardian_4" ,
    url: "/src/utils/iconsRank/SeasonalRank2-4.webp"},
  { name: "Guardian_5" ,
    url: "/src/utils/iconsRank/SeasonalRank2-5.webp"},

  { name: "Crusader_1" ,
    url: "/src/utils/iconsRank/SeasonalRank3-1.webp"},
  { name: "Crusader_2" ,
    url: "/src/utils/iconsRank/SeasonalRank3-2.webp"},
  { name: "Crusader_3" ,
    url: "/src/utils/iconsRank/SeasonalRank3-3.webp"},
  { name: "Crusader_4" ,
    url: "/src/utils/iconsRank/SeasonalRank3-4.webp"},
  { name: "Crusader_5" ,
    url: "/src/utils/iconsRank/SeasonalRank3-5.webp"},

  { name: "Archon_1",
    url: "/src/utils/iconsRank/SeasonalRank4-1.webp" },
  { name: "Archon_2" ,
    url: "/src/utils/iconsRank/SeasonalRank4-2.webp"},
  { name: "Archon_3",
    url: "/src/utils/iconsRank/SeasonalRank4-3.webp" },
  { name: "Archon_4" ,
    url: "/src/utils/iconsRank/SeasonalRank4-4.webp"},
  { name: "Archon_5" ,
    url: "/src/utils/iconsRank/SeasonalRank4-5.webp"},

  { name: "Legend_1" ,
    url: "/src/utils/iconsRank/SeasonalRank5-1.webp"},
  { name: "Legend_2" ,
    url: "/src/utils/iconsRank/SeasonalRank5-2.webp"},
  { name: "Legend_3" ,
    url: "/src/utils/iconsRank/SeasonalRank5-3.webp"},
  { name: "Legend_4",
    url: "/src/utils/iconsRank/SeasonalRank5-4.webp" },
  { name: "Legend_5" ,
    url: "/src/utils/iconsRank/SeasonalRank5-5.webp"},

  { name: "Ancient_1" ,
    url: "/src/utils/iconsRank/SeasonalRank6-1.webp"},
  { name: "Ancient_2" ,
    url: "/src/utils/iconsRank/SeasonalRank6-2.webp"},
  { name: "Ancient_3" ,
    url: "/src/utils/iconsRank/SeasonalRank6-3.webp"},
  { name: "Ancient_4",
    url: "/src/utils/iconsRank/SeasonalRank6-4.webp" },
  { name: "Ancient_5",
    url: "/src/utils/iconsRank/SeasonalRank6-5.webp" },
  { name: "Divine_1" ,
    url: "/src/utils/iconsRank/SeasonalRank7-1.webp"},
  { name: "Divine_2" ,
    url: "/src/utils/iconsRank/SeasonalRank7-2.webp"},
  { name: "Divine_3",
    url: "/src/utils/iconsRank/SeasonalRank7-3.webp" },
  { name: "Divine_4" ,
    url: "/src/utils/iconsRank/SeasonalRank7-4.webp"},
  { name: "Divine_5" ,
    url: "/src/utils/iconsRank/SeasonalRank7-5.webp"},
  { name: "Immortal" ,
    url: "/src/utils/iconsRank/SeasonalRankTop0.webp"},
];
